// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV8LXe0GFNeaG9ra-1m1JEkGNgGZPABGA',
    appId: '1:384709551060:web:7711ddbeeb470df44dac41',
    messagingSenderId: '384709551060',
    projectId: 'musicapp-19bff',
    authDomain: 'musicapp-19bff.firebaseapp.com',
    storageBucket: 'musicapp-19bff.firebasestorage.app',
    measurementId: 'G-L8CEM02H1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCdmACidjnT6F4i31CXHAel7Wxk3AFmpE',
    appId: '1:384709551060:android:63123c5f4379cd784dac41',
    messagingSenderId: '384709551060',
    projectId: 'musicapp-19bff',
    storageBucket: 'musicapp-19bff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqpeWER5h7LVTJ3vfkAfEdmPwd83xqmxw',
    appId: '1:384709551060:ios:3391e13693577d634dac41',
    messagingSenderId: '384709551060',
    projectId: 'musicapp-19bff',
    storageBucket: 'musicapp-19bff.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqpeWER5h7LVTJ3vfkAfEdmPwd83xqmxw',
    appId: '1:384709551060:ios:3391e13693577d634dac41',
    messagingSenderId: '384709551060',
    projectId: 'musicapp-19bff',
    storageBucket: 'musicapp-19bff.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV8LXe0GFNeaG9ra-1m1JEkGNgGZPABGA',
    appId: '1:384709551060:web:d40856e126b592e04dac41',
    messagingSenderId: '384709551060',
    projectId: 'musicapp-19bff',
    authDomain: 'musicapp-19bff.firebaseapp.com',
    storageBucket: 'musicapp-19bff.firebasestorage.app',
    measurementId: 'G-3VCKWT66FJ',
  );
}
